# Structured guide data for the FastPIFU skill generator. SPECIALTIES is appended to.

SPECIALTIES.append({
 "slug": "dermatology", "Specialty": "Dermatology",
 "cond_blurb": "skin cancers and pre-cancers (melanoma, cSCC, BCC, actinic keratosis, SCC in situ), multiple atypical moles, post-skin-lesion surgery, inflammatory skin disease, acne, isotretinoin and patch tests",
 "traps": [
   "A skin-cancer patient who could self-examine scar sites and nodes — PSFU/PIFU may replace routine review (MelFo model), but frailty may make even that unnecessary.",
   "An inflammatory-disease patient on systemics who is stable: annual nurse monitoring or PIFU may suffice; do not assume guideline-frequency bloods are required (check the SMPC).",
   "A condition excluded by the local threshold policy — do not offer PIFU; discharge.",
 ],
 "rules": [
   "Do not offer PIFU for conditions excluded by the local threshold policy — rationale: these should be discharged, not retained on a pathway.",
 ],
 "conditions": [
  {"file":"general-principles","name":"General principles (Dermatology follow-up)",
   "scope":"Cross-cutting GIRFT/BAD 'top tips' for deciding follow-up in any dermatology pathway. Read alongside the condition-specific files.",
   "pifu":["Follow-up is for monitoring response to treatment, discharge is not yet possible, and the patient can be educated to use PIFU safely.",
           "Stable patient on long-term medication who could be reviewed virtually or via PIFU rather than routine F2F.",
           "Frail patient after skin cancer who can self-examine nodes/scar sites — urgent PSFU/PIFU if concerns (MelFo model)."],
   "retain":["Monitoring genuinely requires scheduled specialist review or bloods mandated by the SMPC.",
             "Unstable disease, or a patient unable to self-monitor or contact the service."],
   "discharge":["Diagnosed patient with a management plan and back-up flare plan, safely manageable in primary care (ideally after experienced-consultant review).",
                "Condition excluded by the local threshold policy.",
                "Benign lesion/BCC excised — write with results, no follow-up."],
   "source":"GIRFT/BAD Dermatology Follow-Up 'Top Tips' (2023, 2026 updates). " },
  {"file":"melanoma","name":"Melanoma",
   "scope":"Cutaneous melanoma, staged follow-up per NICE NG14 and the MelFo reduced-frequency schedule. Early detection of recurrence allows prompt treatment; self-examination supports PSFU/PIFU.",
   "pifu":["Patient can self-examine and reliably detect lymph nodes/recurrence — a PSFU/PIFU arrangement (as in MelFo) allows safe follow-up with fewer appointments.",
           "Stage IB–IIC during the lower-frequency tail of the schedule where self-surveillance is appropriate."],
   "retain":["Within the scheduled-review window for the stage (e.g. Stage IIA six-monthly for 2 years then annual to year 5; Stage IIB/IIC four-monthly tapering).",
             "Stage IIIA–IV: personalised follow-up as guided by the SSMDT; on or considered for adjuvant therapy; unresected disease.",
             "Imaging due per guideline."],
   "discharge":["Stage 0: single education appointment at one year, then discharge.",
                "Stage IA: discharge at end of year one.",
                "Completion of the stage-specific schedule (e.g. Stage IB at year 5; Stage IIIA–IIID/resected IV not on adjuvant at end of schedule)."],
   "data":[("Stage (AJCC)","Sets the entire follow-up schedule"),("Whether on adjuvant therapy","Stage III–IV on adjuvant needs SSMDT-led review"),("Self-examination capability","Underpins safe PSFU/PIFU")],
   "interval":"Stage-dependent per NICE NG14 / MelFo; PIFU/PSFU replaces routine slots where self-surveillance is reliable.",
   "source":"NICE NG14 (2022); MelFo Study UK. "+SOURCE },
  {"file":"cutaneous-scc","name":"Cutaneous squamous cell carcinoma (cSCC)",
   "scope":"cSCC follow-up by risk category (BAD 2020). High-risk may be safely managed with PSFU.",
   "pifu":["High-risk cSCC where the patient can self-monitor — evidence supports safe PSFU (GIRFT further-faster).",
           "Patient too frail for further treatment — close routine follow-up may be replaced by patient-centred PSFU/PIFU."],
   "retain":["High-risk: four-monthly for 12 months then six-monthly for 12 months (to 2 years).",
             "Very high-risk: four-monthly for 24 months then six-monthly for 12 months (to 3 years).",
             "Metastatic: three-monthly for 24 months then six-monthly for 36 months, with longer review per patient factors."],
   "discharge":["Low-risk cSCC: single post-treatment appointment then discharge.",
                "Completion of the risk-category schedule (high-risk at 2 years, very-high at 3 years)."],
   "data":[("Risk category (low/high/very-high/metastatic)","Sets schedule and PSFU suitability"),("Frailty / fitness for further treatment","May favour patient-centred reduced follow-up")],
   "source":"BAD cSCC guideline (2020). "+SOURCE },
  {"file":"basal-cell-carcinoma","name":"Basal cell carcinoma (BCC)",
   "scope":"BCC follow-up (BAD 2021). Most single BCCs are discharged post-operatively.",
   "pifu":["History of multiple BCCs with reliable self-monitoring — PIFU/PSFU with access if new lesions appear."],
   "retain":["Multiple BCCs likely to develop further tumours/recurrence within 12 months — offer at least yearly follow-up.",
             "Excised high-risk BCC with close histological margin (<1 mm) — refer for MDT discussion."],
   "discharge":["Single BCC excised — discharge postoperatively with a standard results/sun-protection letter and stitch-removal advice.",
                "Frail patient with limited life expectancy and slow-growing BCC where conservative management is chosen."],
   "data":[("Single vs multiple BCC","Determines follow-up vs discharge"),("Histological margin","<1 mm high-risk needs MDT")],
   "source":"BAD BCC guideline (2021). "+SOURCE },
  {"file":"actinic-keratosis","name":"Actinic keratosis (AK)",
   "scope":"AK is usually treated and discharged at first secondary-care appointment (BAD 2017).",
   "pifu":["High risk of cancer — consider PIFU post-treatment with self-surveillance education."],
   "retain":["Very high risk (e.g. transplant recipient) — scheduled follow-up."],
   "discharge":["Treat on first appointment and discharge with prevention/skin-surveillance information (the default for most AK)."],
   "source":"BAD AK guideline (2017). "+SOURCE },
  {"file":"scc-in-situ","name":"SCC in situ (Bowen's disease)",
   "scope":"Often treated in primary care; secondary-care follow-up driven by cancer risk.",
   "pifu":["High risk of cancer — consider PIFU post-treatment."],
   "retain":["Very high risk — scheduled follow-up."],
   "discharge":["Standard-risk SCC in situ treated — discharge with advice."],
   "source":SOURCE },
  {"file":"multiple-atypical-moles","name":"Multiple atypical moles",
   "scope":"Usually education and discharge with self-surveillance, per local policy.",
   "pifu":["Reliable self-surveillance with access back if concerns."],
   "retain":["Very high risk (strong personal or family history of melanoma) — scheduled follow-up."],
   "discharge":["Suspected cancer excluded — educate and discharge with self-surveillance."],
   "source":SOURCE },
  {"file":"post-skin-lesion-surgery","name":"Post-skin-lesion surgery",
   "scope":"Follow-up after excision of benign lesions/BCCs.",
   "pifu":["Not routinely required for benign lesions/BCCs."],
   "retain":["Targeted follow-up only for dysplasia/carcinoma on histology or wound concern."],
   "discharge":["Benign lesion/BCC excised — write with results and information, no follow-up."],
   "source":SOURCE },
  {"file":"inflammatory-skin-disease","name":"Inflammatory skin disease (psoriasis, eczema)",
   "scope":"Psoriasis/eczema managed topically, on phototherapy, or on systemics/biologics.",
   "pifu":["Moderate-to-severe disease controlled on maximal topical therapy who may need systemics in future — consider PIFU.",
           "Post-phototherapy and clear, or stable — consider PIFU.",
           "Stable on systemics/biologics with limited comorbidities — annual nurse monitoring with telephone consultation may be adequate."],
   "retain":["Not clear after phototherapy and may need systemics — follow-up to discuss.",
             "On systemics with comorbidities — personalise follow-up; bloods only as the SMPC requires (often less than guideline frequency)."],
   "discharge":["Topically managed and stable — education, written treatment and flare plans, discharge to GP."],
   "source":"GIRFT/BAD; NICE/BAD eczema & psoriasis pathways. "+SOURCE },
  {"file":"acne","name":"Acne",
   "scope":"Most acne is managed in primary care per NICE; secondary care for specified indications.",
   "pifu":["Generally not a PIFU pathway — see isotretinoin file if relevant."],
   "retain":["Severe acne or under specialist treatment requiring review."],
   "discharge":["Not severe or unsuitable for isotretinoin — discharge with advice per NICE; consider spironolactone via primary care/A&G."],
   "source":"NICE acne guidance. "+SOURCE },
  {"file":"isotretinoin","name":"Isotretinoin",
   "scope":"Isotretinoin course follow-up, governed by the MHRA pregnancy-prevention programme.",
   "pifu":["Not a PIFU pathway during the course."],
   "retain":["Follow-up per pregnancy-prevention programme for those of childbearing potential; one F2F appointment mandated by MHRA, others may be virtual. New MHRA rules allow less-than-monthly review for some very-low-pregnancy-risk patients."],
   "discharge":["Course complete and criteria met — discharge."],
   "source":"MHRA isotretinoin guidance. "+SOURCE },
  {"file":"patch-tests","name":"Patch tests",
   "scope":"Allergen identification via patch testing.",
   "pifu":["Where appropriate, after relevant allergen identified and avoidance/treatment plan given — consider PIFU."],
   "retain":["Ongoing diagnostic uncertainty requiring further testing."],
   "discharge":["Relevant allergen identified, avoidance and treatment plan provided — discharge where appropriate. (Code patch-test visits as PT, not follow-up.)"],
   "source":SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "ent", "Specialty": "ENT",
 "cond_blurb": "endoscopic sinus surgery, nasal septoplasty, functional septorhinoplasty, paediatric otitis media with effusion (grommets) and paediatric day-case adenotonsillectomy",
 "traps": [
   "A post-nasal-surgery patient with splints still in — first review is for splint/wound, not yet a discharge point.",
   "A paediatric OME child whose hearing has NOT improved at the six-week test, or who has concerning social/neurodevelopmental factors — not routine PIFU.",
 ],
 "rules": [
   "Paediatric pathways (OME, adenotonsillectomy) use nurse-led discharge against BADS criteria; PIFU is conditional on the six-week hearing test and absence of concerning social/neurodevelopmental factors.",
 ],
 "conditions": [
  {"file":"endoscopic-sinus-surgery","name":"Endoscopic sinus surgery",
   "scope":"Day-case functional endoscopic sinus surgery for chronic rhinosinusitis after a ≥3-month trial of medical therapy.",
   "pifu":["After the first post-operative face-to-face follow-up at 3–6 weeks — PIFU available for one year."],
   "retain":["Within the first post-operative review window (first follow-up at 3–6 weeks).",
             "Ongoing surgical concern at first review."],
   "discharge":["Recovered with no concerns at the end of the PIFU year."],
   "interval":"First follow-up 3–6 weeks post-op; PIFU available for 1 year thereafter.",
   "source":SOURCE },
  {"file":"nasal-septoplasty","name":"Nasal septoplasty",
   "scope":"Day-case septoplasty for nasal obstruction after a 3-month trial of medical therapy.",
   "pifu":["Not routinely offered — discharge if no concerns."],
   "retain":["First follow-up at 1–2 weeks if nasal splints used; second follow-up at 6 weeks–3 months."],
   "discharge":["No concerns at the second follow-up (6 weeks–3 months) — discharge, no routine PIFU."],
   "interval":"1–2 weeks (if splints) then 6 weeks–3 months; no routine PIFU.",
   "source":SOURCE },
  {"file":"functional-septorhinoplasty","name":"Functional septorhinoplasty",
   "scope":"Day-case functional septorhinoplasty for nasal obstruction after a 3-month trial of medical therapy.",
   "pifu":["Not routinely offered — discharge if no concerns."],
   "retain":["First follow-up at 1–2 weeks if nasal splints used; second follow-up at 6 weeks–3 months."],
   "discharge":["No concerns at the second follow-up (6 weeks–3 months) — discharge, no routine PIFU."],
   "interval":"1–2 weeks (if splints) then 6 weeks–3 months; no routine PIFU.",
   "source":SOURCE },
  {"file":"paediatric-ome","name":"Paediatric otitis media with effusion (OME)",
   "scope":"Children with ≥3-month hearing difficulty, grommets (±adenoidectomy) where hearing aids declined/unsuitable. Paediatric pathway.",
   "pifu":["Discharge with PIFU after the six-week hearing test, provided hearing has improved."],
   "retain":["Face-to-face follow-up with hearing test at 6 weeks post-surgery (default).",
             "Hearing NOT improved at the six-week test.",
             "Concerning social factors or neurodevelopmental conditions."],
   "discharge":["Nurse-led discharge if BADS criteria met and recovery uncomplicated."],
   "interval":"Hearing test at 6 weeks post-surgery; PIFU thereafter if hearing improved.",
   "source":SOURCE },
  {"file":"paediatric-adenotonsillectomy","name":"Paediatric day-case adenotonsillectomy",
   "scope":"Day-case adenotonsillectomy for persistent OSA, recurrent tonsillitis or other commissioned indications. Paediatric pathway.",
   "pifu":["No routine outpatient follow-up or PIFU."],
   "retain":["Complication or failure to meet nurse-led discharge (BADS) criteria."],
   "discharge":["Nurse-led discharge if BADS criteria met."],
   "source":SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "gastroenterology", "Specialty": "Gastroenterology",
 "cond_blurb": "stable cirrhosis, hyperferritinaemia/haemochromatosis, hepatitis B, auto-immune liver disease, MASLD, alcohol-related liver disease, inflammatory bowel disease and iron-deficiency anaemia",
 "traps": [
   "A chronic liver patient who 'feels well' but is due surveillance (6-monthly USS/AFP, fibrosis re-assessment) — surveillance is independent of clinic and must continue.",
   "Any patient found to be cirrhotic on assessment — moves to the stable-cirrhosis surveillance pathway regardless of how they present.",
   "A stable patient who lacks a safe/robust remote-monitoring or DNA-tracking system — without it, PIFU/remote monitoring is not safe.",
 ],
 "rules": [
   "PIFU/remote monitoring for chronic liver disease is only safe where a robust surveillance and DNA-tracking system exists — rationale: surveillance results, not clinic attendance, drive escalation.",
   "Any patient shown to be cirrhotic enters the stable-cirrhosis surveillance pathway — rationale: HCC and portal-hypertension risk require mandated surveillance.",
 ],
 "conditions": [
  {"file":"stable-cirrhosis","name":"Stable cirrhosis",
   "scope":"Patients with established cirrhosis needing structured surveillance. PIFU runs in parallel to surveillance, which is independent of clinic.",
   "pifu":["Stable cirrhosis with a safe and robust PIFU/remote-monitoring and DNA-tracking system in place — review can be annual, surveillance results or symptoms trigger earlier review. PIFU can be lifelong.",
           "Patient educated on signs/symptoms of concern and how to contact the service."],
   "retain":["No safe/robust remote-monitoring or DNA-tracking system available.",
             "Decompensation, new complication, or surveillance finding requiring assessment.",
             "Minimum 6-monthly review of relevant investigations and symptoms is still required (delivered remotely where examination is not needed)."],
   "discharge":["Not typically discharged — surveillance is lifelong; consider DISCHARGE only if care is formally transferred elsewhere."],
   "data":[("Confirmation of cirrhosis & aetiology","Defines surveillance need"),("HCC-surveillance eligibility","Drives 6-monthly USS/AFP"),("Presence of a safe remote-monitoring/DNA system","Pre-condition for PIFU")],
   "interval":"6-monthly investigations/symptom review (USS+AFP 6-monthly if HCC surveillance indicated); portal-hypertension and bone-health checks at mandated intervals. Annual review if robust PIFU/remote monitoring in place.",
   "source":SOURCE },
  {"file":"hyperferritinaemia-haemochromatosis","name":"Hyperferritinaemia / haemochromatosis (HH)",
   "scope":"High ferritin and HFE-related haemochromatosis. Much can be triaged via A&G; confirmed C282Y HH needs secondary-care follow-up.",
   "pifu":["Non-cirrhotic C282Y HH on maintenance — life-long follow-up delivered remotely/PIFU where a safe/secure system exists; bloods ≥6-monthly in maintenance, venesection when bloods mandate."],
   "retain":["Induction-phase venesection (weekly until ferritin <50).",
             "Raised fibrosis markers or other positive findings needing further assessment.",
             "Ongoing risk factors (MASLD/ARLD) needing repeat fibrosis assessment.",
             "Cirrhotic on assessment — enter the stable-cirrhosis pathway."],
   "discharge":["Hyperferritinaemia without HH/significant iron overload — manage in primary care via A&G (do not bring into secondary-care follow-up)."],
   "data":[("HFE genotype (C282Y)","Confirms HH"),("TF sats & ferritin","Stage and treatment phase"),("Fibrosis assessment","Cirrhosis triggers surveillance")],
   "interval":"Maintenance bloods ≥6-monthly; venesection as bloods mandate. Life-long for non-cirrhotic C282Y HH.",
   "source":SOURCE },
  {"file":"hepatitis-b","name":"Hepatitis B",
   "scope":"Chronic HBV referred with markers of current infection. Much is automatable / remote.",
   "pifu":["Virally suppressed, stable, adherent, no renal risk factors — remote/PIFU monitoring, 6–12 monthly (12-monthly for suitable stable patients). Suitable for automation."],
   "retain":["Meets treatment criteria / starting treatment — monitor first 3–6 months to confirm adherence and viral suppression.",
             "Not yet on treatment — HBV DNA and ALT every 6–12 months until criteria met.",
             "Cirrhosis or non-cirrhotic at-risk-of-HCC — 6-monthly liver USS + AFP; cessation of antiviral therapy must be managed by secondary care with close relapse monitoring.",
             "Planned cancer treatment/immunosuppression with positive HBV markers — secondary-care treatment plan."],
   "discharge":["Generally not discharged while monitoring/surveillance indicated; A&G manages those not needing secondary care."],
   "data":[("Treatment criteria status","On/eligible vs monitor"),("Viral suppression & adherence","Determines monitoring frequency"),("Cirrhosis / HCC-risk status","Drives 6-monthly USS+AFP")],
   "interval":"HBsAg ±quantification 12-monthly; DNA/ALT 6–12 monthly; HCC USS+AFP 6-monthly if indicated.",
   "source":SOURCE },
  {"file":"autoimmune-liver-disease","name":"Auto-immune liver disease",
   "scope":"AILD referred with abnormal LFTs and/or positive auto-antibodies; treatment and monitoring to complete biochemical response (CBR).",
   "pifu":["Achieved CBR with a safe system for long-term management — enrol into PIFU/remote monitoring (potentially life-long), including planned consideration of immunosuppression withdrawal after a suitable interval and criteria.",
           "Stable once CBR reached — clinic only every 6–12 months."],
   "retain":["First 12 months: bloods every 3 months to confirm CBR, then every 3–6 months.",
             "Active titration or not yet at CBR.",
             "Cirrhosis on assessment — stable-cirrhosis surveillance pathway."],
   "discharge":["Not typically discharged while immunosuppression/monitoring continues."],
   "data":[("CBR status","Gateway to PIFU"),("Bone-health & fibrosis assessment","Mandated monitoring"),("Cirrhosis status","Triggers surveillance")],
   "interval":"3-monthly bloods in year 1, then 3–6 monthly; clinic 6–12 monthly once stable.",
   "source":SOURCE },
  {"file":"masld","name":"MASLD (metabolic dysfunction-associated steatotic liver disease)",
   "scope":"Fatty liver referred for fibrosis evaluation; disposition driven by fibrosis score.",
   "pifu":["Intermediate fibrosis score — may be suitable for PIFU until a repeat fibrosis assessment is performed."],
   "retain":["Proven cirrhosis — stable-cirrhosis surveillance pathway.",
             "Intermediate fibrosis needing repeat assessment in 1–2 years."],
   "discharge":["Low fibrosis score — discharge back to primary care, with possible repeat fibrosis assessment in ~3 years (sooner if ongoing risk factors).",
                "No/minimal fibrosis — discharge with advice on future re-assessment."],
   "data":[("Fibrosis score (e.g. FibroScan/ELF)","Determines disposition"),("Ongoing metabolic risk factors","Set re-assessment interval")],
   "interval":"Repeat fibrosis assessment 1–2 years (intermediate) or ~3 years (low/ongoing risk).",
   "source":SOURCE },
  {"file":"alcohol-related-liver-disease","name":"Alcohol-related liver disease (ArLD)",
   "scope":"ArLD without decompensation; disposition driven by fibrosis stage and risk factors. Signpost to alcohol services.",
   "pifu":["Non-cirrhotic needing planned-interval repeat fibrosis assessment with a safe/robust PIFU/remote-monitoring system — suitable for PIFU or remote monitoring.",
           "Cirrhotic — followed per stable-cirrhosis pathway (which itself supports PIFU where safe)."],
   "retain":["6-monthly follow-up for patients diagnosed at, or on subsequent, fibrosis re-assessment with cirrhosis.",
             "Intermediate fibrosis — repeat assessment in 1–2 years (could be primary care).",
             "No safe/robust monitoring system."],
   "discharge":["Planned repeat fibrosis assessment can be done in primary care — discharge back with advice; no/minimal fibrosis re-assess in ~3 years."],
   "data":[("Fibrosis stage","Cirrhotic vs not"),("Ongoing alcohol use / risk","Re-assessment interval")],
   "interval":"6-monthly if cirrhotic; repeat fibrosis 1–2 years (intermediate) / ~3 years (low).",
   "source":SOURCE },
  {"file":"ibd","name":"Inflammatory bowel disease (IBD)",
   "scope":"Suspected/confirmed IBD; stable patients suit remote monitoring and PIFU. Surveillance independent of clinic.",
   "pifu":["Stable IBD after initial/subsequent follow-up — PIFU pathway (may be lifelong), with a 12-monthly virtual review and clear written flare information.",
           "Medicines and faecal-calprotectin monitoring and cancer surveillance deliverable remotely/asynchronously."],
   "retain":["Newly confirmed/active disease — face-to-face assessment, treatment and medicines review.",
             "Surveillance/monitoring due (medicines monitoring, faecal calprotectin, cancer surveillance per BSG).",
             "Nutrition, bone-health, mental-health or pre-conception needs requiring review."],
   "discharge":["IBD excluded and symptoms resolved — discharge to primary care."],
   "data":[("Disease activity/stability","Active vs stable"),("Surveillance schedule (BSG)","Cancer surveillance timing"),("Flare-plan & contact info given","PIFU pre-condition")],
   "interval":"12-monthly virtual review on PIFU; surveillance per BSG, independent of clinic.",
   "source":"BSG IBD guidelines. "+SOURCE },
  {"file":"iron-deficiency-anaemia","name":"Iron deficiency anaemia (IDA)",
   "scope":"Suspected/confirmed IDA, largely a direct-to-test then primary-care-monitored pathway.",
   "pifu":["Not a secondary-care PIFU pathway — monitoring is in primary care after investigation."],
   "retain":["Diagnostic uncertainty after investigation — further tests (CT colonography, capsule endoscopy, renal-tract USS) before discharge.",
             "Meets Faster Diagnostic Standard — urgent suspected-cancer pathway."],
   "discharge":["Non-significant findings after DTT/investigation — discharge to primary care with a management plan, safety netting and FBC monitoring at 3/6/12/24 months per NICE.",
                "Not IDA, or previously investigated IDA — discharge via A&G."],
   "data":[("Confirmed iron deficiency (iron studies)","Confirms diagnosis"),("DTT outcome/histology","Significant vs non-significant"),("FDS criteria","Cancer pathway trigger")],
   "interval":"Primary-care FBC at 3, 6, 12, 24 months (NICE).",
   "source":"NICE/BSG IDA guidance. "+SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "general-surgery", "Specialty": "General surgery",
 "cond_blurb": "general-surgery day-case pathways (inguinal and paraumbilical hernia, laparoscopic cholecystectomy, pilonidal sinus) and colorectal pathways (haemorrhoids, anal fissure, anal fistula, colorectal resection)",
 "traps": [
   "Rectal bleeding not yet investigated before a haemorrhoid/fissure procedure — straight-to-test flexible sigmoidoscopy is required first.",
   "A high-complication-risk hernia patient — needs a targeted 6–8 week face-to-face review, not no-follow-up.",
   "A colorectal-resection specimen showing cancer/dysplasia — moves to active cancer surveillance, not discharge.",
 ],
 "rules": [
   "Ensure rectal bleeding has been investigated (straight-to-test flexible sigmoidoscopy) before any haemorrhoid/fissure pathway — rationale: exclude malignancy.",
   "A resection/excision specimen with dysplasia or carcinoma triggers targeted oncological follow-up, never routine discharge.",
 ],
 "conditions": [
  {"file":"inguinal-hernia","name":"Inguinal hernia repair",
   "scope":"Elective day-case inguinal hernia repair.",
   "pifu":["Not offered — discharge with no PIFU."],
   "retain":["Early wound problem (access via day surgery)."],
   "discharge":["Uncomplicated repair — no routine follow-up; discharge. Enrol in the BHS hernia registry for PROMs."],
   "source":SOURCE },
  {"file":"paraumbilical-hernia","name":"Paraumbilical hernia repair",
   "scope":"Elective day-case paraumbilical hernia repair.",
   "pifu":["Not offered — discharge with no PIFU."],
   "retain":["High risk of complications — targeted face-to-face appointment at 6–8 weeks.",
             "Early wound problem (access via day surgery)."],
   "discharge":["Uncomplicated small primary hernia — no routine follow-up; discharge. Enrol in the BHS hernia registry."],
   "source":SOURCE },
  {"file":"laparoscopic-cholecystectomy","name":"Laparoscopic cholecystectomy",
   "scope":"Elective day-case laparoscopic cholecystectomy.",
   "pifu":["PIFU for six months for recurrent symptoms, jaundice or diarrhoea."],
   "retain":["Targeted follow-up for dysplasia or carcinoma found in the specimen."],
   "discharge":["Uncomplicated — no routine follow-up; specialist-nurse phone line for early advice."],
   "interval":"PIFU for 6 months.",
   "source":SOURCE },
  {"file":"pilonidal-sinus","name":"Pilonidal sinus surgery",
   "scope":"Day-case pilonidal sinus surgery.",
   "pifu":["PIFU for three months."],
   "retain":["Flap procedures or open wounds — face-to-face appointment at 6–8 weeks."],
   "discharge":["Excision and primary closure of a simple sinus — no face-to-face follow-up; discharge to PIFU."],
   "interval":"PIFU for 3 months.",
   "source":SOURCE },
  {"file":"haemorrhoids-operative","name":"Haemorrhoids (operative treatment)",
   "scope":"Day-case operative haemorrhoid treatment. Rectal bleeding must be investigated first.",
   "pifu":["No PIFU."],
   "retain":["Targeted follow-up for dysplasia/carcinoma in the specimen.",
             "Early wound problem or pain control (access via day surgery)."],
   "discharge":["Uncomplicated — no routine follow-up; discharge."],
   "source":SOURCE },
  {"file":"haemorrhoids-outpatient","name":"Haemorrhoids (outpatient banding/injection)",
   "scope":"Outpatient banding or injection. Rectal bleeding must be investigated first.",
   "pifu":["PIFU for three months."],
   "retain":["Treating clinician believes further treatment will be necessary."],
   "discharge":["Default is no follow-up if treatment complete and bleeding investigated."],
   "interval":"PIFU for 3 months.",
   "source":SOURCE },
  {"file":"anal-fissure-medical","name":"Anal fissure (medical management)",
   "scope":"Medically managed anal fissure. Rectal bleeding must be investigated first.",
   "pifu":["PIFU for three months."],
   "retain":["Digital rectal examination has not been possible — follow-up required."],
   "discharge":["Default is no follow-up where examination complete and bleeding investigated."],
   "interval":"PIFU for 3 months.",
   "source":SOURCE },
  {"file":"anal-fissure-operative","name":"Anal fissure (operative treatment)",
   "scope":"Day-case operative anal fissure treatment (Botox, lateral sphincterotomy, advancement flap).",
   "pifu":["PIFU for three months (after Botox injections — no face-to-face follow-up)."],
   "retain":["Face-to-face appointment at 6–8 weeks after lateral anal sphincterotomy or advancement flap."],
   "discharge":["Uncomplicated Botox — discharge to PIFU."],
   "interval":"PIFU for 3 months.",
   "source":SOURCE },
  {"file":"anal-fistula","name":"Anal fistula",
   "scope":"Day-case anal fistula surgery; up-to-date MRI for complex/recurrent disease.",
   "pifu":["PIFU for three months (after lay-open of a low simple fistula)."],
   "retain":["Face-to-face appointment at 6–8 weeks after lay-open of a complex fistula, seton insertion, or sphincter-preserving techniques."],
   "discharge":["Lay-open of low simple fistula — discharge to PIFU."],
   "interval":"PIFU for 3 months.",
   "source":SOURCE },
  {"file":"colorectal-resection","name":"Colorectal resection",
   "scope":"Inpatient elective colorectal resection (not the cancer-surgery referral pathway). Disposition depends on pathology.",
   "pifu":["No PIFU; all patients have ward/CNS access for early wound or stoma problems."],
   "retain":["All patients: 6–8 week face-to-face follow-up.",
             "Colorectal cancer: active surveillance for 5 years with risk-stratified CT and CEA arranged remotely.",
             "Ulcerative colitis: keep under review."],
   "discharge":["Crohn's: discharge and transfer to gastroenterology.",
                "Diverticular disease: discharge."],
   "interval":"6–8 week review for all; cancer surveillance 5 years.",
   "source":SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "gynaecology", "Specialty": "Gynaecology",
 "cond_blurb": "pelvic organ prolapse (conservative, pessary and surgical pathways)",
 "traps": [
   "A patient close to the BMI surgical cut-off — may be listed conditionally to allow time for weight loss; not a straightforward PIFU.",
   "A post-operative patient where early recurrence or complication is the concern — direct access back to the surgical team is needed.",
 ],
 "rules": [
   "BMI > 35 may make a patient ineligible for surgery — ensure this is communicated and conservative options (physio, pessary) are offered.",
 ],
 "conditions": [
  {"file":"pelvic-organ-prolapse","name":"Pelvic organ prolapse (POP)",
   "scope":"Symptomatic POP managed conservatively, with pessaries, or surgically. Asymptomatic incidental prolapse does not require referral.",
   "pifu":["Patient close to the BMI cut-off listed for surgery, to allow time for weight loss.",
           "Conservatively managed patient who may want further assessment/treatment.",
           "Post-operative patient, to assess for early recurrence — with clear contact information and direct access back to the surgical team. PIFU limited to 6–12 months."],
   "retain":["Nurse-led TWOC and post-operative care.",
             "Immediate post-operative complications — seen by urogynaecologist or specialist nurse with direct link to the surgical team.",
             "Complex non-surgical or complex surgical cases discussed at the urogynaecology MDT."],
   "discharge":["Asymptomatic incidental prolapse (inside vagina / reaching introitus) — no referral; lifestyle advice in primary care.",
                "Symptoms resolved after conservative management with no ongoing specialist need."],
   "data":[("POP-Q or objective assessment","Severity & management"),("BMI","Surgical eligibility"),("Management option chosen","Conservative/pessary/surgery")],
   "interval":"PIFU limited to 6–12 months.",
   "source":SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "ophthalmology", "Specialty": "Ophthalmology",
 "cond_blurb": "cataract surgery, age-related macular degeneration (AMD), diabetic macular oedema (DMO) and glaucoma, including virtual/asynchronous review pathways",
 "traps": [
   "A treated macular patient who looks inactive but is in the strict treat-and-extend window — monitoring must continue at interval before discharge.",
   "A glaucoma patient whose follow-up interval and discharge eligibility are defined by GIRFT Best Practice for Glaucoma Services, not by clinic convenience.",
   "PDR/R3a or new wet AMD needs urgent face-to-face assessment, never PIFU.",
 ],
 "rules": [
   "Glaucoma follow-up intervals and discharge are governed by GIRFT Best Practice for Glaucoma Services — rationale: risk-stratified intervals, not ad hoc review.",
   "Suspected wet AMD requires urgent referral/assessment within one working day — never a PIFU disposition.",
 ],
 "conditions": [
  {"file":"cataract-surgery","name":"Cataract surgery",
   "scope":"Routine and complex cataract surgery; most routine patients are discharged to optometry.",
   "pifu":["Not a PIFU pathway — routine patients discharge to community optometry with urgent/CUES return route."],
   "retain":["Complex patient or serious/unstable ocular co-morbidity — optometrist-commissioned follow-up or HCP/consultant-led hospital appointment.",
             "Minor complication or IOP check — ±1–2 day hospital visit.",
             "Fellow-eye surgery requiring F2F per ocular complexity."],
   "discharge":["Routine patient — discharge to sight test with optometry data return; urgent/CUES pathway if needed."],
   "source":SOURCE },
  {"file":"amd","name":"Age-related macular degeneration (AMD)",
   "scope":"Dry and wet AMD; wet AMD is an injection pathway with high-volume virtual review.",
   "pifu":["Not a PIFU pathway — managed via virtual review and strict treat-and-extend, then discharge with self-monitoring."],
   "retain":["Wet AMD on treatment — virtual review every interval (treat-and-extend); first injection within 14 days of detection/referral.",
             "Suspected wet AMD — urgent assessment within one working day."],
   "discharge":["Inactive treated disease — monitor 3-monthly for two years for reactivation, then discharge with self-monitoring/red-flag advice.",
                "Permanent structural damage / no further treatment — discharge to routine sight test with ECLO/low-vision support.",
                "Dry AMD — no referral; regular sight test with diet/lifestyle/monitoring advice."],
   "interval":"Treat-and-extend on treatment; post-discharge self-monitoring with red-flag advice.",
   "source":SOURCE },
  {"file":"diabetic-macular-oedema","name":"Diabetic macular oedema (DMO)",
   "scope":"DMO identified at sight test or DESP; asynchronous/virtual review with injection where indicated.",
   "pifu":["Not a PIFU pathway — virtual/asynchronous review and treat-and-extend, then discharge back to DESP when stable."],
   "retain":["CRT >400 µm — offered IVT; strict treat-and-extend with certainty of appointments.",
             "PDR/R3a — appointment within six weeks, must be face-to-face.",
             "DESP-referred DMO — appointment at HES within 13 weeks (may be virtual)."],
   "discharge":["Stable maculopathy and retinopathy — discharge back to DESP; inform GP and optometrist with ECLO/low-vision support if needed."],
   "interval":"Six-monthly DAVRAP retinal monitoring (individualised) while in service.",
   "source":SOURCE },
  {"file":"glaucoma","name":"Glaucoma",
   "scope":"Glaucoma and ocular hypertension via single-point-of-access triage and a Diagnostic Asynchronous Virtual Review Assessment Pathway (DAVRAP). Intervals and discharge per GIRFT Best Practice for Glaucoma Services.",
   "pifu":["Not a PIFU pathway in the conventional sense — virtual review at risk-stratified intervals; face-to-face capacity focused on higher-risk patients."],
   "retain":["Use the follow-up intervals defined in GIRFT Best Practice for Glaucoma Services (e.g. OHT/suspect COAG/COAG by conversion, IOP control and RAG risk).",
             "Patients receiving laser/surgical intervention as indicated by virtual review."],
   "discharge":["Use the discharge criteria defined in GIRFT Best Practice for Glaucoma Services (e.g. new patients with no OHT/no glaucoma 'disease' — discharge after first attendance with A&G letter and recommend regular community sight test; treated PACS-plus after LPI or cataract surgery)."],
   "interval":"Per GIRFT Best Practice for Glaucoma Services follow-up interval tables (months by conversion/IOP control/RAG risk).",
   "source":"GIRFT Best Practice for Glaucoma Services. "+SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "omfs", "Specialty": "Oral and maxillofacial surgery",
 "cond_blurb": "OMFS surgical pathways (dentoalveolar surgery, jaw cysts, facial fractures, orthognathic osteotomy, skin lesions) and non-surgical oral-mucosal conditions, TMJ problems and myofascial pain",
 "traps": [
   "An irradiated patient or one on bisphosphonates/antiresorptive/anti-angiogenic drugs — needs an 8-week MRONJ-aware review, not the no-follow-up default.",
   "A large jaw cyst or odontogenic keratocyst — needs radiographic follow-up (and annual review to 5 years for keratocysts), unlike small cysts which discharge.",
 ],
 "rules": [
   "Dentoalveolar surgery in irradiated patients or those on bisphosphonate/antiresorptive/anti-angiogenic drugs follows the SDCEP MRONJ-risk pathway with 8-week review — never the routine no-follow-up default.",
 ],
 "conditions": [
  {"file":"dentoalveolar-surgery","name":"Dentoalveolar surgery (incl. MRONJ-risk and soft-tissue procedures)",
   "scope":"Simple dentoalveolar surgery (extractions, surgical removals, apical surgery, exposures), soft-tissue procedures, and the higher-risk MRONJ subgroup.",
   "pifu":["Salivary duct manipulation ± stone removal — PIFU pathway."],
   "retain":["Irradiated patients, or patients on bisphosphonates/antiresorptive/anti-angiogenic drugs — follow-up at 8 weeks per SDCEP 'Oral health management of patients at risk of MRONJ'.",
             "Patients on orthodontic pathways — appropriate orthodontic review."],
   "discharge":["Routine simple dentoalveolar surgery — no surgical follow-up required.",
                "Soft-tissue procedures (polyps, mucoceles) — telephone/letter with histology, no follow-up."],
   "source":"BAOMS SIGs; SDCEP MRONJ guidance. "+SOURCE },
  {"file":"jaw-cysts","name":"Jaw cysts and odontogenic keratocysts",
   "scope":"Enucleation of jaw cysts with primary closure; odontogenic keratocysts (incl. syndromic, e.g. Gorlin's) need longer surveillance.",
   "pifu":["Not a PIFU pathway — radiographic surveillance where indicated."],
   "retain":["Large cysts (≥2 cm): face-to-face appointment at 6–12 months for a radiograph to check bone healing/tooth eruption.",
             "Odontogenic keratocysts: as for large cysts, plus annual radiographic review for 5 years to check for recurrence."],
   "discharge":["Small cysts (≤2 cm diameter): straight to discharge, no follow-up — letter/telephone call with pathology results."],
   "interval":"Large cysts 6–12 months; keratocysts annually to 5 years.",
   "source":"BAOMS SIGs. "+SOURCE },
  {"file":"facial-fractures","name":"Facial fractures (mandibular, condyle, zygomatic, orbital)",
   "scope":"Open reduction/fixation or closed reduction of facial fractures. Excludes children with developing dentition / growing condyles, and late orbital problems (e.g. enophthalmos).",
   "pifu":["Orbital fractures — discharge to PIFU after the early review and orthoptic follow-up."],
   "retain":["Mandibular fractures: follow-up at 10–14 days and final follow-up at 8–12 weeks.",
             "Orbital fractures: follow-up at 10–14 days plus orthoptic-team follow-up per unit protocol."],
   "discharge":["Zygomatic fractures: follow-up at 10–14 days then discharge."],
   "interval":"Early review 10–14 days; mandibular final review 8–12 weeks.",
   "source":"BAOMS SIGs. "+SOURCE },
  {"file":"orthognathic-osteotomy","name":"Orthognathic osteotomy (single-jaw and bimaxillary)",
   "scope":"Sagittal-split / vertical-ramus / Le Fort I osteotomy on the orthognathic pathway. Excludes osteotomies requiring post-operative intermaxillary fixation.",
   "pifu":["Not a PIFU pathway — handed to the orthodontic team."],
   "retain":["Follow-up at 1 week post-operatively."],
   "discharge":["After the 1-week review — discharge to the orthodontic team."],
   "interval":"1-week post-op review.",
   "source":"BAOMS SIGs. "+SOURCE },
  {"file":"skin-lesions","name":"Head and neck skin lesions (OMFS)",
   "scope":"Skin lesions of the head and neck (melanoma, cSCC, BCC, AK, SCC in situ). Excludes major head-and-neck cancer.",
   "pifu":["Follow the GIRFT/BAD Dermatology follow-up protocols — see the dermatology skill files for the per-lesion disposition (PSFU/PIFU where self-monitoring is reliable)."],
   "retain":["Per dermatology risk-category schedules."],
   "discharge":["Per dermatology pathways (e.g. low-risk cSCC, single BCC)."],
   "source":"2023 GIRFT/BAD Follow-up 'Top Tips' (2026 updates). "+SOURCE },
  {"file":"oral-mucosal-conditions","name":"Oral mucosal conditions (dry mouth, geographic tongue, recurrent oral ulceration, oral lichen planus)",
   "scope":"Non-surgical oral-mucosal conditions: dry mouth, geographic tongue (erythema migrans), recurrent oral ulceration, and oral lichen planus (reticular and erosive).",
   "pifu":["Erosive oral lichen planus (no dysplasia) — once treatment is established, PIFU is suitable."],
   "retain":["Erosive OLP while treatment is being established (treatments vary from advice to systemics).",
             "Diagnostic uncertainty requiring biopsy/bloods."],
   "discharge":["Dry mouth, geographic tongue, recurrent oral ulceration, reticular oral lichen planus — history/clinical appearance (±tests), give advice, no follow-up."],
   "source":"NICE; BAOMS SIGs. "+SOURCE },
  {"file":"tmj-and-myofascial-pain","name":"Temporomandibular joint problems and myofascial pain",
   "scope":"TMJ problems (myogenous/arthrogenous) and myofascial pain, including Botox for those who have failed self-supported management.",
   "pifu":["Botox for myofascial pain after failed self-management — PIFU pathway (Botox given at first follow-up)."],
   "retain":["TMJ problems — follow the Faster Diagnostic Standard (FDS) guidance for the relevant diagnosis."],
   "discharge":["Managed with advice and self-supported management succeeding."],
   "source":"FDS guidance; BAOMS SIGs. "+SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "orthopaedics", "Specialty": "Orthopaedics",
 "cond_blurb": "elective joint replacement (hip, knee), ACL reconstruction, foot-and-ankle (bunion, injections), shoulder arthroscopy, and hand pathways (Dupuytren's, ganglion, trigger digit, carpal tunnel, hand trauma)",
 "traps": [
   "A post-operative patient NOT meeting expected recovery milestones — keep in timed follow-up rather than moving to PIFU/discharge.",
   "A diagnostic (rather than therapeutic) injection — needs telephone follow-up to act on the result, not a therapeutic PIFU.",
   "A complex/skin-graft hand case — needs face-to-face consultant follow-up, unlike simple cases.",
 ],
 "rules": [
   "Post-operative PIFU/discharge applies only when the patient is meeting expected recovery milestones — rationale: deviation needs scheduled review.",
 ],
 "conditions": [
  {"file":"total-hip-replacement","name":"Elective primary total hip replacement",
   "scope":"Uncomplicated elective primary THR (the ~85% standard-recovery majority).",
   "pifu":["Safety-netting and PIFU for 1 year after the single post-operative review."],
   "retain":["One appointment (virtual or F2F) at 6 weeks–3 months post-surgery with the surgical team (CNS/ACP/physio/SCP). No repeat X-ray."],
   "discharge":["Recovered and meeting milestones at end of PIFU year."],
   "interval":"One review at 6 weeks–3 months; PIFU for 1 year.",
   "source":SOURCE },
  {"file":"total-knee-replacement","name":"Elective primary total and uni knee replacement",
   "scope":"Uncomplicated elective primary total/uni knee replacement (the ~85% standard-recovery majority).",
   "pifu":["Safety-netting and PIFU for 1 year after the single post-operative review."],
   "retain":["One appointment (virtual or F2F) at 6 weeks–3 months post-surgery with the surgical team."],
   "discharge":["Recovered and meeting milestones at end of PIFU year."],
   "interval":"One review at 6 weeks–3 months; PIFU for 1 year.",
   "source":SOURCE },
  {"file":"acl-reconstruction","name":"Anterior cruciate ligament reconstruction",
   "scope":"Uncomplicated ACL reconstruction (the ~75% standard-recovery majority).",
   "pifu":["PIFU with access to therapy-led provision for 12 months post-op."],
   "retain":["One appointment (virtual/F2F) at 6 weeks–3 months and a 9-month follow-up with the surgical team."],
   "discharge":["Recovered and meeting milestones at end of the pathway."],
   "interval":"Reviews at 6 weeks–3 months and 9 months; PIFU 12 months.",
   "source":SOURCE },
  {"file":"hallux-valgus-rigidus","name":"Hallux valgus/rigidus (bunion) surgery",
   "scope":"Day-case bunion surgery after community non-surgical management.",
   "pifu":["PIFU option available only if the patient is not meeting expected milestones."],
   "retain":["Dressing clinic at 1–2 weeks (nurse-led, surgeon available); 6-week post-surgery appointment with follow-up X-ray only if needed.",
             "Patient not meeting expected milestones."],
   "discharge":["Meeting expected milestones at 6 weeks — discharge."],
   "interval":"1–2 weeks dressing clinic; 6-week review.",
   "source":SOURCE },
  {"file":"foot-ankle-injections","name":"Foot and ankle injections",
   "scope":"Outpatient therapeutic or diagnostic foot/ankle injections.",
   "pifu":["Therapeutic injection (~90%) — PIFU for 6–9 months."],
   "retain":["Diagnostic injection (<10%) — telephone follow-up to act on the result."],
   "discharge":["Therapeutic injection successful at end of PIFU window."],
   "interval":"PIFU for 6–9 months (therapeutic).",
   "source":SOURCE },
  {"file":"shoulder-arthroscopy","name":"Shoulder arthroscopy (rotator cuff repair / subacromial decompression)",
   "scope":"Day-case shoulder arthroscopy. Recovery milestones gate PIFU.",
   "pifu":["Subacromial decompression: PIFU at 6 weeks (after the 1st follow-up) unless not recovering as expected.",
           "Rotator cuff repair: PIFU at 6 months (after the 2nd follow-up) unless not recovering as expected."],
   "retain":["Subacromial decompression: 1st appointment at 6–8 weeks post-op.",
             "Rotator cuff repair: 1st at 6–8 weeks and 2nd at 3–6 months post-op; 3rd at 12 months if not recovering as expected.",
             "Not recovering as expected."],
   "discharge":["Recovered and meeting milestones at the relevant PIFU point."],
   "interval":"SAD: 1st at 6–8 wk then PIFU. RCR: 6–8 wk and 3–6 mo then PIFU.",
   "source":SOURCE },
  {"file":"dupuytrens","name":"Dupuytren's disease",
   "scope":"Percutaneous fasciotomy or day-case surgery for Dupuytren's.",
   "pifu":["PIFU (12 months) for patients not ready for or requiring surgery.",
           "PIFU (6–12 weeks) for non-complex post-operative cases."],
   "retain":["Skin graft / complex cases — face-to-face follow-up with the consultant.",
             "Virtual review by surgeon/ESP where suitable (outpatient cases)."],
   "discharge":["Simple case recovered after virtual review."],
   "interval":"PIFU 12 months (pre-surgery) or 6–12 weeks (post-op non-complex).",
   "source":"GIRFT hand pathway. "+SOURCE },
  {"file":"ganglion","name":"Ganglion",
   "scope":"Day-case ganglion aspiration/excision; many aspirated and discharged same day.",
   "pifu":["PIFU — 3 months for simple aspirations and 3 months for surgical cases."],
   "retain":["Wound therapy/review only if patient/surgical team are concerned."],
   "discharge":["Nurse-led discharge; sutures (if any) removed in primary care."],
   "interval":"PIFU 3 months.",
   "source":"GIRFT hand pathway. "+SOURCE },
  {"file":"trigger-digit","name":"Adult trigger digit",
   "scope":"Day-case surgery for adult trigger digit after up to 2 cortisone injections.",
   "pifu":["PIFU 3 months only if the patient is not progressing as expected."],
   "retain":["Wound therapy/review only if patient/surgical team are concerned; suture removal at GP/local arrangements if required.",
             "Not progressing as expected."],
   "discharge":["Progressing as expected — discharge."],
   "interval":"PIFU 3 months (conditional).",
   "source":"GIRFT hand pathway. "+SOURCE },
  {"file":"hand-trauma","name":"Hand lacerations / cuts / trauma / bite wounds",
   "scope":"ED/MIU-presenting hand lacerations, cuts, trauma and bite wounds.",
   "pifu":["Discharge or PIFU at surgeon discretion."],
   "retain":["At surgeon discretion where ongoing review is needed."],
   "discharge":["At surgeon discretion where recovery is uncomplicated."],
   "source":"GIRFT hand pathway. "+SOURCE },
  {"file":"carpal-tunnel","name":"Carpal tunnel syndrome",
   "scope":"Day-case carpal tunnel decompression after community management/single steroid injection.",
   "pifu":["PIFU 3 months only if the patient is not progressing as expected."],
   "retain":["Hand therapy and face-to-face appointment if ongoing problems (CRPS, nerve damage, scar issues), or after neurolysis/flexor tenosynovectomy.",
             "Not progressing as expected."],
   "discharge":["Progressing as expected after 10–14 day suture removal (at GP/local) — discharge."],
   "interval":"Suture removal 10–14 days; PIFU 3 months (conditional).",
   "source":"GIRFT hand pathway. "+SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "spinal", "Specialty": "Spinal",
 "cond_blurb": "lumbar facet-joint (medial branch block) and nerve-root-block injections, posterior lumbar decompression/discectomy, and the adolescent idiopathic scoliosis pathway",
 "traps": [
   "An injection patient with a diagnostic response but returning pain — offer denervation (facet) or consider surgery (nerve root); injections should NOT be repeated.",
   "An AIS patient where PIFU is being used as a substitute for discharge — it must run alongside planned monitoring, not replace appropriate discharge.",
 ],
 "rules": [
   "Spinal injections should NOT be repeated — rationale: a diagnostic response with recurrent pain warrants denervation or surgical consideration, not repeat injection.",
   "PIFU is used whenever clinically appropriate but never as an alternative to discharge.",
 ],
 "conditions": [
  {"file":"facet-joint-injections","name":"Lumbar medial branch block (facet joint injections)",
   "scope":"Day-case lumbar facet-joint injection, often directly listed from a virtual MDT; no clinical tabletop review required.",
   "pifu":["6-month PIFU (communicated to the patient at the start of the pathway); no clinical tabletop review required."],
   "retain":["Diagnostic response but pain returns — offer denervation (do not repeat the injection)."],
   "discharge":["At end of the 6-month PIFU period if no further intervention needed."],
   "interval":"6-month PIFU.",
   "source":SOURCE },
  {"file":"lumbar-nerve-root-block","name":"Lumbar nerve root block (epidural)",
   "scope":"Day-case lumbar nerve-root block, often directly listed from a virtual MDT; no clinical tabletop review required.",
   "pifu":["6-month PIFU (communicated at the start of the pathway); no clinical tabletop review required."],
   "retain":["Diagnostic response but pain returns — consider surgery (do not repeat the injection)."],
   "discharge":["At end of the 6-month PIFU period if no further intervention needed."],
   "interval":"6-month PIFU.",
   "source":SOURCE },
  {"file":"lumbar-decompression-discectomy","name":"Posterior lumbar decompression / discectomy",
   "scope":"Posterior lumbar decompression or discectomy (2nd priority after injections). Benchmark: 2 appointments pre-procedure and 1 post-procedure.",
   "pifu":["6-month PIFU duration (communicated at the beginning)."],
   "retain":["Wound review in primary care at 2 weeks; 2–3-week post-op virtual physio follow-up; 6–8-week virtual post-op follow-up with the surgical team."],
   "discharge":["At end of the 6-month PIFU period once recovered."],
   "interval":"Wound 2 wk; physio 2–3 wk; surgical 6–8 wk; PIFU 6 months.",
   "source":SOURCE },
  {"file":"adolescent-idiopathic-scoliosis","name":"Adolescent idiopathic scoliosis (AIS)",
   "scope":"AIS pathway (British Scoliosis Society). PIFU used whenever clinically appropriate, not as an alternative to discharge. Paediatric/adolescent pathway.",
   "pifu":["1 year of PIFU with access into the service after the 1-year follow-up.",
           "Non-operative: nurse-led virtual monitoring pathway; CNS-led remote appointment and X-ray update."],
   "retain":["8-week face-to-face follow-up + safety netting; 1-year face-to-face follow-up with same-day X-ray; 2-year X-ray (no appointment) with results letter.",
             "Planned monitoring or bracing pathway; MDT review with action plans."],
   "discharge":["Close PIFU and discharge after the 2-year X-ray if stable."],
   "interval":"8-week and 1-year F2F; 2-year X-ray; 1-year PIFU.",
   "source":"British Scoliosis Society; Further Faster Spinal Services Handbook. "+SOURCE },
 ]})

SPECIALTIES.append({
 "slug": "urology", "Specialty": "Urology",
 "cond_blurb": "benign urology conditions (stones, bladder-outlet obstruction, erectile dysfunction, LUTS/overactive bladder, bladder pain syndrome, pelvic floor disorders, long-term ISC, post-Peyronie's, recurrent UTI) and urological cancer remote-monitoring (bladder, prostate, kidney)",
 "traps": [
   "A recurrent-UTI patient with pain on voiding plus back/loin pain or temperature — needs urgent medical attention (NHS 111/GP), not PIFU.",
   "A cancer-surveillance patient who feels well but is due interval imaging/PSA — surveillance is the point of the pathway and must continue.",
 ],
 "rules": [
   "Recurrent UTI with pain on voiding plus back/loin pain or fever requires urgent medical attention (NHS 111/GP) — never a PIFU disposition.",
 ],
 "conditions": [
  {"file":"benign-conditions","name":"Benign urology conditions (PIFU table)",
   "scope":"Benign conditions managed on discharge-PIFU or review-PIFU with defined patient triggers for contact and a discharge timeline. Each sub-condition below names its trigger and timeline.",
   "pifu":["Stones, post-stone-surgery (discharge-PIFU): triggers — pain, bleeding and/or infection (post-op); new/continuing loin pain, unexplained fevers, antibiotic-unresponsive UTI, new haematuria (review-PIFU). Stones review-PIFU: non-F2F clinical review at 2 years with CT.",
           "Post-operative bladder-outlet obstruction (discharge-PIFU): trigger — poor flow and/or ongoing frequency/urgency/incontinence after 3 months despite treatment. Discharge at 6 months.",
           "Erectile dysfunction treatment (discharge-PIFU): trigger — treatment not successful, or pain/swelling on administration. Discharge at 6 months.",
           "LUTS / overactive bladder on Botox (review-PIFU): trigger — worsening LUTS; seen F2F on the cystoscopy/Botox list.",
           "Bladder pain syndrome / interstitial cystitis (discharge-PIFU): trigger — significant change/progression of pain, urgency, frequency, proven recurrent UTIs. Discharge at 2 years.",
           "Pelvic floor disorders / self-change ring pessary (discharge-PIFU): trigger — persistence/worsening for which the patient wants further assessment. Discharge at 2 years.",
           "Long-term ISC (discharge-PIFU): trigger — difficulty passing catheter, recurrent UTIs, haematuria. Discharge at 1 year.",
           "Post-Peyronie's corrective surgery (discharge-PIFU): trigger — pain/swelling after 4 weeks, failure of correction, or declining function at 3 months warranting intervention. Discharge at 3 months.",
           "Recurrent UTI on management pathway (discharge-PIFU): trigger — recurrent UTI-suggestive symptoms or visible haematuria despite appropriate treatment. Discharge to GP at 1 year."],
   "retain":["Review-PIFU conditions with a planned non-F2F or list-based review (e.g. stones 2-year CT review; LUTS/OAB Botox on the cystoscopy list)."],
   "discharge":["At the condition-specific timeline above (3 months–2 years) if no triggers met.",
                "Recurrent UTI — discharge back to GP at 1 year."],
   "data":[("Specific condition","Selects trigger set and timeline"),("Time since procedure/treatment","Determines discharge point"),("Red-flag symptoms (loin pain+fever)","Diverts recurrent-UTI patients to urgent care")],
   "interval":"Discharge timeline 3 months–2 years by condition; contact via telephone/app with imaging arranged as required.",
   "source":SOURCE },
  {"file":"cancer-remote-monitoring","name":"Urological cancer follow-up and remote monitoring (bladder, prostate, kidney)",
   "scope":"Risk-stratified cancer surveillance suited to CNS-led remote monitoring (app/letter/telephone by patient choice). Surveillance is independent of routine clinic attendance.",
   "pifu":["Remote monitoring (app/letter/telephone) by an appropriate clinician who reviews the result and contacts the patient — the standard model for stable cancer surveillance."],
   "retain":["Bladder (cystectomy, by risk): bloods/CTU+thorax/USS/GFR at 3, 6, 12 months and yearly to 6 years (high-risk CTU at 3/6/12 months); then 2-yearly surveillance CT-TAP per shared decision.",
             "Prostate on active surveillance: PSA 3-monthly, MRI at 1 year. Post-radical treatment: PSA + function impact at 6–12 weeks then 6-monthly with a treatment-team re-referral threshold.",
             "Kidney (by risk): CT chest/abdomen/pelvis at intervals (low-risk 1/3/5 years; intermediate 6/12 months then yearly to 5 years; high-risk 3/6/12 months, 18 months, yearly to 5 years then 2-yearly).",
             "Bosniak 2F cysts: CT with contrast at 6, 18, 30, 48 months."],
   "discharge":["Bladder: at 6 years move to 2-yearly GP-arranged review (or discharge per shared decision).",
                "Prostate: discharge at 5 years' follow-up.",
                "Kidney low-risk: discharge at 5 years; intermediate/high-risk: shared decision on ongoing surveillance after 5 years per fitness/wishes.",
                "Bosniak 2F: discharge if no change at 48 months."],
   "data":[("Cancer type & risk stratification","Sets imaging schedule"),("Time since treatment","Determines surveillance vs discharge"),("Patient fitness/wishes","Shared decision after 5 years")],
   "interval":"Per cancer-type schedule above; remote monitoring by CNS/appropriate clinician.",
   "source":SOURCE },
 ]})
